user:
  avatar_profile: "100x100"
  per_page: 5
  trainee_param: "trainee_page"
  supervisor_param: "supervisor_page"
  user_subject:
    per_page: 2
course:
  per_page: 5
  status_label:
    not_started: "info"
    in_process: "success"
    closed: "danger"
subject:
  per_page: 5
  subject_param: "subject_page"
activity:
  activity_param: "activity_page"
course_subject:
  status:
    in_process: "in_process"
    closed: "closed"
  status_label:
    not_started: "info"
    in_process: "success"
    closed: "danger"
  subject_course_param: "subject_course_page"
  task_subject_param: "task_subject_page"
public_activity:
  avatar_owner: "30x30"
task:
  per_page: 5

build_task: 1
least_task: 1
assign_trainee: 1
remove_trainee: 2
mail_from: "tms61@gmail.com"
layout: "mailer"
